/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAtendimentosRouteImport } from './routes/_authenticated/atendimentos'
import { Route as AuthenticatedCentralRouteImport } from './routes/_authenticated/central'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedNovoAlertaRouteImport } from './routes/_authenticated/novo-alerta'
import { Route as AuthenticatedAlertaIdRouteImport } from './routes/_authenticated/alerta.$id'
import { Route as AuthenticatedOcorrenciaIdRouteImport } from './routes/_authenticated/ocorrencia.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAtendimentosRoute =
  AuthenticatedAtendimentosRouteImport.update({
    id: '/atendimentos',
    path: '/atendimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCentralRoute = AuthenticatedCentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNovoAlertaRoute = AuthenticatedNovoAlertaRouteImport.update({
  id: '/novo-alerta',
  path: '/novo-alerta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertaIdRoute = AuthenticatedAlertaIdRouteImport.update({
  id: '/alerta/$id',
  path: '/alerta/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOcorrenciaIdRoute =
  AuthenticatedOcorrenciaIdRouteImport.update({
    id: '/ocorrencia/$id',
    path: '/ocorrencia/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/atendimentos': typeof AuthenticatedAtendimentosRoute
  '/central': typeof AuthenticatedCentralRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/novo-alerta': typeof AuthenticatedNovoAlertaRoute
  '/alerta/$id': typeof AuthenticatedAlertaIdRoute
  '/ocorrencia/$id': typeof AuthenticatedOcorrenciaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/atendimentos': typeof AuthenticatedAtendimentosRoute
  '/central': typeof AuthenticatedCentralRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/novo-alerta': typeof AuthenticatedNovoAlertaRoute
  '/alerta/$id': typeof AuthenticatedAlertaIdRoute
  '/ocorrencia/$id': typeof AuthenticatedOcorrenciaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/atendimentos': typeof AuthenticatedAtendimentosRoute
  '/_authenticated/central': typeof AuthenticatedCentralRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/novo-alerta': typeof AuthenticatedNovoAlertaRoute
  '/_authenticated/alerta/$id': typeof AuthenticatedAlertaIdRoute
  '/_authenticated/ocorrencia/$id': typeof AuthenticatedOcorrenciaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/atendimentos'
    | '/central'
    | '/historico'
    | '/novo-alerta'
    | '/alerta/$id'
    | '/ocorrencia/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/atendimentos'
    | '/central'
    | '/historico'
    | '/novo-alerta'
    | '/alerta/$id'
    | '/ocorrencia/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/atendimentos'
    | '/_authenticated/central'
    | '/_authenticated/historico'
    | '/_authenticated/novo-alerta'
    | '/_authenticated/alerta/$id'
    | '/_authenticated/ocorrencia/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/atendimentos': {
      id: '/_authenticated/atendimentos'
      path: '/atendimentos'
      fullPath: '/atendimentos'
      preLoaderRoute: typeof AuthenticatedAtendimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/central': {
      id: '/_authenticated/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof AuthenticatedCentralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/novo-alerta': {
      id: '/_authenticated/novo-alerta'
      path: '/novo-alerta'
      fullPath: '/novo-alerta'
      preLoaderRoute: typeof AuthenticatedNovoAlertaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerta/$id': {
      id: '/_authenticated/alerta/$id'
      path: '/alerta/$id'
      fullPath: '/alerta/$id'
      preLoaderRoute: typeof AuthenticatedAlertaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ocorrencia/$id': {
      id: '/_authenticated/ocorrencia/$id'
      path: '/ocorrencia/$id'
      fullPath: '/ocorrencia/$id'
      preLoaderRoute: typeof AuthenticatedOcorrenciaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtendimentosRoute: typeof AuthenticatedAtendimentosRoute
  AuthenticatedCentralRoute: typeof AuthenticatedCentralRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedNovoAlertaRoute: typeof AuthenticatedNovoAlertaRoute
  AuthenticatedAlertaIdRoute: typeof AuthenticatedAlertaIdRoute
  AuthenticatedOcorrenciaIdRoute: typeof AuthenticatedOcorrenciaIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtendimentosRoute: AuthenticatedAtendimentosRoute,
  AuthenticatedCentralRoute: AuthenticatedCentralRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedNovoAlertaRoute: AuthenticatedNovoAlertaRoute,
  AuthenticatedAlertaIdRoute: AuthenticatedAlertaIdRoute,
  AuthenticatedOcorrenciaIdRoute: AuthenticatedOcorrenciaIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
