/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedNovoAlertaRouteImport } from './routes/_authenticated/novo-alerta'
import { Route as AuthenticatedAlertaIdRouteImport } from './routes/_authenticated/alerta.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNovoAlertaRoute = AuthenticatedNovoAlertaRouteImport.update({
  id: '/novo-alerta',
  path: '/novo-alerta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertaIdRoute = AuthenticatedAlertaIdRouteImport.update({
  id: '/alerta/$id',
  path: '/alerta/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/novo-alerta': typeof AuthenticatedNovoAlertaRoute
  '/alerta/$id': typeof AuthenticatedAlertaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/novo-alerta': typeof AuthenticatedNovoAlertaRoute
  '/alerta/$id': typeof AuthenticatedAlertaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/novo-alerta': typeof AuthenticatedNovoAlertaRoute
  '/_authenticated/alerta/$id': typeof AuthenticatedAlertaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/historico' | '/novo-alerta' | '/alerta/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/historico' | '/novo-alerta' | '/alerta/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/historico'
    | '/_authenticated/novo-alerta'
    | '/_authenticated/alerta/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/novo-alerta': {
      id: '/_authenticated/novo-alerta'
      path: '/novo-alerta'
      fullPath: '/novo-alerta'
      preLoaderRoute: typeof AuthenticatedNovoAlertaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerta/$id': {
      id: '/_authenticated/alerta/$id'
      path: '/alerta/$id'
      fullPath: '/alerta/$id'
      preLoaderRoute: typeof AuthenticatedAlertaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedNovoAlertaRoute: typeof AuthenticatedNovoAlertaRoute
  AuthenticatedAlertaIdRoute: typeof AuthenticatedAlertaIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedNovoAlertaRoute: AuthenticatedNovoAlertaRoute,
  AuthenticatedAlertaIdRoute: AuthenticatedAlertaIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
